version: '3.8'
services:
  mentora-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:80
      - NEXT_PUBLIC_API_BASE_URL=/api/v1
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - mentora-network
networks:
  mentora-network:
    driver: bridge